##---IMPORTS

import os
from ..settings import *

##---CONSTANTS

CONFIG_TEXT = """## apache config file for the spikesorting evaluation website
## generated by ./deploy/create_httpd_conf.py

<VirtualHost *:{svr_port}>

  # server and doc-root
  ServerName {svr_name}
  ServerAlias {svr_name}
  ServerAdmin {svr_email}
  DocumentRoot {dir_root}

  # media directory
  Alias {url_media} {dir_media}
  <Directory {dir_media}>
    Order deny,allow
    Allow from all
  </Directory>

  # static directory
  Alias {url_static} {dir_static}
  <Directory {dir_static}>
    Order deny,allow
    Allow from all
  </Directory>

  # WSGI scripts
  WSGIDaemonProcess spike display-name=spike
  WSGIProcessGroup spike

  WSGIScriptAlias / {dir_root}/deploy/wsgi.py
  <Directory {dir_root}/deploy>
    Order deny,allow
    Allow from all
  </Directory>

</VirtualHost>

""".format(dir_root=PROJECT_ROOT, dir_media=MEDIA_ROOT, url_media=MEDIA_URL,
           dir_static=STATIC_ROOT, url_static=STATIC_URL)

##----FUNCTIONS

def create_apache_conf(
  svr_name='spike.g-node.org',
  svr_email='pmeier82@googlemail.com',
  svr_port='8001'):
    if not os.path.exists('../apache'):
        os.mkdir('../apache')
    if not os.path.isdir('../apache'):
        raise IOError('../apache exists but is not a directory!')
    with open('../apache/apache.conf', 'w') as conf_file:
        conf_file.write(
            CONFIG_TEXT.format(
                svr_name=svr_name,
                svr_email=svr_email,
                svr_port=svr_port))

##---MAIN

if __name__ == '__main__':
    create_apache_conf()
