##---IMPORTS

import os
from django.conf import settings

##---CONSTANTS

CONF_TEXT = """## apache config file for the spikesorting evaluation website
## generated by ./deploy/create_httpd_conf.py

<VirtualHost *:{svr_port}>

  # server and doc-root
  ServerName {svr_name}
  ServerAlias {svr_name}
  ServerAdmin {svr_email}
  DocumentRoot {PROJECT_ROOT}

  # media directory
  Alias {MEDIA_URL} {MEDIA_ROOT}
  <Directory {MEDIA_ROOT}>
    Order deny,allow
    Allow from all
  </Directory>

  # static directory
  Alias {STATIC_URL} {STATIC_ROOT}
  <Directory {STATIC_ROOT}>
    Order deny,allow
    Allow from all
  </Directory>

  # WSGI scripts
  WSGIDaemonProcess spike display-name=spike
  WSGIProcessGroup spike
  WSGIScriptAlias / {PROJECT_ROOT}/deploy/wsgi.py
  <Directory {PROJECT_ROOT}/deploy>
    Order deny,allow
    Allow from all
  </Directory>

</VirtualHost>

"""

##---FUNCTIONS

def create_apache_conf(
  svr_name='spike.g-node.org',
  svr_email='pmeier82@googlemail.com',
  svr_port='8001'):
    apache_dir = os.path.join(getattr(settings, 'PROJECT_ROOT'), 'apache')
    if not os.path.exists(apache_dir):
        os.mkdir(apache_dir)
    if not os.path.isdir(apache_dir):
        raise IOError('{apache_dir} exists but is not a directory!'.format
            (apache_dir))

    with open(os.path.join(apache_dir, 'apache.conf'), 'w') as conf_file:
        conf_file.write(
            CONF_TEXT.format(
                svr_name=svr_name,
                svr_email=svr_email,
                svr_port=svr_port,
                PROJECT_ROOT=getattr(settings, 'PROJECT_ROOT'),
                MEDIA_ROOT=getattr(settings, 'MEDIA_ROOT'),
                MEDIA_URL=getattr(settings, 'MEDIA_URL'),
                STATIC_ROOT=getattr(settings, 'STATIC_ROOT'),
                STATIC_URL=getattr(settings, 'STATIC_URL')))

##---MAIN

if __name__ == '__main__':
    create_apache_conf()
