##---IMPORTS

import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "spike_g_node_org.settings")

from django.conf import settings

##---CONSTANTS

AP_CFG_TEXT = """## apache config file for the spikesorting evaluation website
## generated by ./deploy/deploy_apache_wsgi.py

<VirtualHost *:{svr_port}>

  # server and doc-root
  ServerName {svr_name}
  ServerAlias {svr_name}
  ServerAdmin {svr_email}
  DocumentRoot {PROJECT_ROOT}

  # logs
  ErrorLog {PROJECT_ROOT}/apache/error.log
  customLog {PROJECT_ROOT}/apache/access.log combined

  # directories
  Alias {MEDIA_URL} {MEDIA_ROOT}
  <Directory {MEDIA_ROOT}>
    Order deny,allow
    Allow from all
  </Directory>
  Alias {STATIC_URL} {STATIC_ROOT}
  <Directory {STATIC_ROOT}>
    Order deny,allow
    Allow from all
  </Directory>

  # wsgi script
  WSGIScriptAlias / {PACKAGE_ROOT}/wsgi.py
  WSGIDaemonProcess spike display-name=spike home={PROJECT_ROOT} processes=5 threads=1 maximum-requests=32 inactivity-timeout=300
  WSGIProcessGroup spike
  <Directory {PACKAGE_ROOT}>
    <Files wsgi.py>
      Order allow,deny
      Allow from all
    </Files>
  </Directory>

</VirtualHost>

"""

##---FUNCTIONS

def create_apache_conf():
    svr_name = raw_input('please provide a server name [spike.g-node.org]:') or 'spike.g-node.org'
    svr_email = raw_input('please provide a server email [noname@%s]:' % svr_name) or 'noname@%s' % svr_name
    svr_port = int(raw_input('pleases provide a server port[80]:') or '80')
    apache_dir = os.path.join(getattr(settings, 'PROJECT_ROOT'), 'apache')
    if not os.path.isdir(apache_dir):
        os.mkdir(apache_dir)
    with open(os.path.join(apache_dir, 'apache.conf'), 'w') as ap_cfg:
        ap_cfg.write(
            AP_CFG_TEXT.format(
                svr_name=svr_name,
                svr_email=svr_email,
                svr_port=svr_port,
                PACKAGE_ROOT=getattr(settings, 'PACKAGE_ROOT'),
                PROJECT_ROOT=getattr(settings, 'PROJECT_ROOT'),
                MEDIA_ROOT=getattr(settings, 'MEDIA_ROOT'),
                MEDIA_URL=getattr(settings, 'MEDIA_URL'),
                STATIC_ROOT=getattr(settings, 'STATIC_ROOT'),
                STATIC_URL=getattr(settings, 'STATIC_URL')))

##---MAIN

if __name__ == '__main__':
    create_apache_conf()
